apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: np5g1dehc-go 
  janus-idp.io/tekton: np5g1dehc-go
  backstage.io/kubernetes-id: np5g1dehc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: np5g1dehc-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  