apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: np5g1dehc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: np5g1dehc-go 
  name: np5g1dehc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: np5g1dehc-go 
